
version: "3.7"
services:
  mysql80:
    image: "mysql:8.0.25"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 2000
      MYSQL_DATABASE: test
      MYSQL_USER: yqy
      MYSQL_PASSWORD: 2000
    ports:
      - "33066:3306"
    volumes:
      - /home/yqy/mysql/data:/var/lib/mysql
      - /home/yqy/mysql/log:/var/log/mysql
      - /home/yqy/mysql/conf:/etc/mysql
      - /home/yqy/mysql/mysql-files:/var/lib/mysql-files
    command:
      --default-authentication-plugin=mysql_native_password